project_id = "ztmmwxfnkydhjdxmdueg"

[functions.send-feedback]
verify_jwt = false

[functions.send-ecoletter]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.process-purchase]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.process-payout]
verify_jwt = false

[functions.subscription-reminders]
verify_jwt = false

[functions.send-seller-onboarding]
verify_jwt = false